### ISSUE TITLE
Cinecoder.Plugin.GpuCodecs package can't be found

### ISSUE THREAD

**Issue by pilzinho** [Cinegy/Cinecoder.Samples#12]
With the latest commits a new package was added that can't be found: Cinecoder.Plugin.GpuCodecs.
Therefore the <Cinecoder.Plugin.GpuCodecs_i.c> cannot be included and Daniel2.SimplePlayerGL.vcxproj cannot be built

**Comment by lewk2** [comment]
All fixed - turns out we had not put GPU codecs onto the public nuget; this is now added, and the build passes compilation again.
