### ISSUE TITLE
Erros when run Daniel2.SimplePlayerGL example

### ISSUE THREAD

**Issue by Human-Friendly** [Cinegy/Cinecoder.Samples#14]
![new errors](https://user-images.githubusercontent.com/48546455/54339706-44574f00-463e-11e9-938b-6b300e5f77c4.png)

The example is compiled successfully but when started it throws this errors. The video we're trying to open is downloaded from the official examples.

**Comment by lewk2** [comment]
Can you confirm if the unit tests pass on your build? What license key do you have injected (although i would expect a different error if your key is expired). The unit tests will certainly complain correctly if the license key you have is expired.

**Comment by Human-Friendly** [comment]
Hello. Yes I confirm that the test is passed. The problem is not with the license key. We are receiving this errors only when trying to use cuda.
