### ISSUE TITLE
Errors on compile Daniel2.SimplePlayerGL example

### ISSUE THREAD

**Issue by Human-Friendly** [Cinegy/Cinecoder.Samples#15]
Hello. We're receiving this erros when trying to compile the newest Daniel2.SimplePlayerGL example.
![errors on compile](https://user-images.githubusercontent.com/48546455/54618303-7a943480-4a6b-11e9-955f-60730976a9a7.png)

**Comment by lewk2** [comment]
Hi, yes - someone managed to commit an internally-available-only library into master, and broke it all - please roll back to the last green commit until we resolve this. 

We will try to make sure such things happen on branches in the future and use pull requests to merge when it is passing tests externally and not just internally :)

**Comment by Human-Friendly** [comment]
Thanks for your fast reply! :)
