### ISSUE TITLE
Seek to frame error

### ISSUE THREAD

**Issue by Human-Friendly** [Cinegy/Cinecoder.Samples#16]
Hello. Sometimes we are receiving this error when using seekToFrame function. It happens very rarely when playing only one video, but when we are playing two or more videos it happens almost every time. 

Best regards,
Martin

![Seek2Frame bug](https://user-images.githubusercontent.com/48546455/56217568-21b8bb80-606c-11e9-8b1d-b006683c7894.jpg)

**Comment by lewk2** [comment]
Is this still a topical problem?

**Comment by lewk2** [comment]
Closed due to inactivity
