### ISSUE TITLE
the Encoded data can't decode by SimpleVideoDecoder

### ISSUE THREAD

**Issue by daiybh** [Cinegy/Cinecoder.Samples#18]
I use the [profile.xml.txt](https://github.com/Cinegy/Cinecoder.Samples/files/3362050/profile.xml.txt)  to Encode  save to test.dn2  ,after use SimpleVideoDecoder to decode this file ,but It can't work.

![image](https://user-images.githubusercontent.com/670317/60713480-c7811580-9f4b-11e9-8cbf-1161301bb915.png)

**Comment by lewk2** [comment]
is this still a topical issue?

**Comment by lewk2** [comment]
Closed due to inactivity
